---
- name: Add required repositories for Debian-based systems
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian" and item is defined
  with_items: "{{ freeradius__packages[ansible_distribution][ansible_distribution_major_version|int]['repositories'] }}"

- name: Add required repositories for RedHat-based systems
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat" and item is defined
  with_items: "{{ freeradius__packages[ansible_distribution][ansible_distribution_major_version|int]['repositories'] }}"

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  when: item is defined
  with_items: "{{ freeradius__packages[ansible_distribution][ansible_distribution_major_version|int]['required_packages'] }}"
  notify: Restart freeradius service

- name: Install main package
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  when: item is defined
  with_items: "{{ freeradius__packages[ansible_distribution][ansible_distribution_major_version|int]['main_package'] }}"
  notify: Restart freeradius service

- name: Create the application folder set
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ freeradius__user }}"
    group: "{{ freeradius__group }}"
    mode: "{{ freeradius__dir_mode }}"
  with_items: "{{ freeradius__directories }}"
  when:
    - freeradius__directories is defined
    - freeradius__directories != ''
  notify: Restart freeradius service
...
