---
- name: Create the system environment file
  template:
    src: "environment.file.j2"
    dest: "{{ freeradius__environment_file }}"
    mode: "{{ freeradius__file_mode }}"
  notify: Restart freeradius service

- name: Check if an init script exists
  stat:
    path: "{{ freeradius__system_init_file }}"
  register: freeradius__init_file

- name: Check if an unit file exists
  stat:
    path: "{{ freeradius__vendor_unit_file }}"
  register: freeradius__unit_file

# Install systemd unit file if required
- name: Create the system unit file
  template:
    src: "unit.file.j2"
    dest: "{{ freeradius__system_unit_file }}"
    mode: "{{ freeradius__file_mode }}"
  notify:
    - Systemd daemon reload
    - Restart freeradius service
  when:
    - freeradius__init_file.stat.exists == False
    - freeradius__unit_file.stat.exists == False

- name: Reload systemd settings
  systemd:
    name: system
    daemon_reload: yes
  notify:
    - Enable freeradius service
    - Start freeradius service
...
