---
- name: Stop freeradius service
  systemd:
    name: "{{ freeradius__service }}"
    state: stopped
    enabled: false
  failed_when: false
  notify:
    - Systemd daemon reload

- name: Delete the system environment files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ freeradius__environment_file }}"
    - "{{ freeradius__system_unit_file }}"
...
