---
- name: Uninstall packages
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ freeradius__packages[ansible_distribution][ansible_distribution_major_version|int]['main_package'] }}"
    - "{{ freeradius__packages[ansible_distribution][ansible_distribution_major_version|int]['required_packages'] }}"

- name: Purge configuration files
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  when: ansible_os_family == "Debian"
  with_items:
    - "{{ freeradius__packages[ansible_distribution][ansible_distribution_major_version|int]['main_package'] }}"
    - "{{ freeradius__packages[ansible_distribution][ansible_distribution_major_version|int]['required_packages'] }}"

- name: Delete the application folders set
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ freeradius__directories }}"
...
