---
- name: Check the OS distribution
  fail:
    msg: "The {{ ansible_distribution }} operating system is not supported!"
  when: not ansible_distribution in freeradius__packages

- name: Check RedHat version
  fail:
    msg: "The {{ ansible_distribution }} version {{ ansible_distribution_major_version }} is not supported!"
  when:
    - ansible_distribution == "RedHat"
    - not ansible_distribution_major_version|int in freeradius__packages.RedHat

- name: Check CentOS version
  fail:
    msg: "The {{ ansible_distribution }} version {{ ansible_distribution_major_version }} is not supported!"
  when:
    - ansible_distribution == "CentOS"
    - not ansible_distribution_major_version|int in freeradius__packages.CentOS

- name: Check Debian version
  fail:
    msg: "The {{ ansible_distribution }} version {{ ansible_distribution_major_version }} is not supported!"
  when:
    - ansible_distribution == "Debian"
    - not ansible_distribution_major_version|int in freeradius__packages.Debian

- name: Check Ubuntu version
  fail:
    msg: "The {{ ansible_distribution }} version {{ ansible_distribution_major_version }} is not supported!"
  when:
    - ansible_distribution == "Ubuntu"
    - not ansible_distribution_major_version|int in freeradius__packages.Ubuntu
...
